@startuml
box #lightgreen
participant Actor
Actor -> App : getStatistics
activate App #gold
App -> PiazzaCtrl :getStatistics
activate PiazzaCtrl #silver
PiazzaCtrl --> App
deactivate PiazzaCtrl

return
@enduml