@startuml
box "Login sequence" #lightgreen
participant Actor
Actor -> App : login \n(with email \n and password)
activate App
App -> PiazzaCtrl : login \n(with email \n and password)
activate PiazzaCtrl
PiazzaCtrl -> User : new user
activate User
User --> PiazzaCtrl
deactivate User
PiazzaCtrl -> PiazzaCtrl : updateLastActive
activate PiazzaCtrl
PiazzaCtrl --> PiazzaCtrl
deactivate PiazzaCtrl
PiazzaCtrl --> App
deactivate PiazzaCtrl
return
@enduml