@startuml
box "Make Post" #lightgreen
participant Actor
Actor -> App : create_post \n(postText \n colourCode \n postType \n threadId \n creator)
activate App
App -> MakePost : showFolders
activate MakePost
MakePost --> App
deactivate MakePost
App -> MakePost : makeThread
activate MakePost
MakePost --> App
deactivate MakePost
App -> MakePost : makePost
activate MakePost
MakePost --> App
deactivate MakePost
App -> MakePost : connectTagsAndPost
activate MakePost
MakePost -> MakePost : makeTag
activate MakePost
MakePost --> MakePost
deactivate MakePost
MakePost --> App
deactivate MakePost 
return
@enduml