@startuml
box "Make Post" #lightgreen
participant Actor
Actor -> App : create_post
activate App
App ->  PiazzaCtrl: showFolders
activate PiazzaCtrl
PiazzaCtrl --> App
deactivate PiazzaCtrl
App --> Actor
Actor -> App: input choose Folder
Actor -> App: input title and text
App -> PiazzaCtrl : makeThread
activate PiazzaCtrl
PiazzaCtrl --> App
deactivate PiazzaCtrl
App -> PiazzaCtrl : makePost
activate PiazzaCtrl
PiazzaCtrl --> App
deactivate PiazzaCtrl
App --> Actor
Actor -> App: input tags
App -> PiazzaCtrl : connectTagsAndPost
activate PiazzaCtrl
PiazzaCtrl -> PiazzaCtrl : makeTag
activate PiazzaCtrl
PiazzaCtrl --> PiazzaCtrl
deactivate PiazzaCtrl
PiazzaCtrl --> App
deactivate PiazzaCtrl
return
@enduml